-- ============================================================
-- TCF Canada AI+ — Insertion des 11 Combinaisons de Sujets
-- Copiez-collez ce code dans votre SQL Editor Supabase
-- ============================================================

INSERT INTO public.subjects (title, task1_prompt, task2_prompt, task3_prompt)
VALUES 
-- Combinaison 11
(
    'Combinaison 11',
    'Vous allez fêter votre anniversaire. Vous envoyez un message à vos amis pour les inviter. Vous leur décrivez le programme de la soirée et leur demandez de l’aide pour l’organisation',
    'Vous avez participé à un concours de cuisine. Sur votre site Internet, vous écrivez un court article pour raconter cette journée. Vous expliquez pourquoi vous avez aimé ou pourquoi vous n’avez pas aimé cette expérience',
    'Tâche 3 : Le travail des jeunes pendant les vacances\n\nDocument 1 :\n« Les vacances sont le moment où les jeunes se détendent après plusieurs mois à l’université. Ils voyagent et profitent des beaux jours. Mais certains étudiants ne prennent pas de vacances et décident de travailler : ils gardent des enfants, servent dans des restaurants ou ramassent des fruits, par exemple. Même si le travail saisonnier présente beaucoup d’avantages, il prive en quelque sorte les jeunes de leur temps libre : ils n’ont pas le temps de se reposer, d’avoir des loisirs et de passer du temps avec leurs proches. De plus, ces emplois d’été sont parfois mal payés, fatigants ou ennuyeux. »\n\nDocument 2 :\n« Pourquoi un grand nombre d’étudiants travaillent-ils pendant les vacances ? Ils font ce choix parce que cette expérience est un premier pas dans le monde professionnel : ils apprennent à se responsabiliser tout en découvrant un métier. Recevoir un salaire est aussi une source de motivation. Travailler pendant les vacances permet à certains d’être indépendants financièrement des parents : ils vont utiliser cet argent pour voyager ou se faire plaisir. Pour d’autres, il s’agit d’une nécessité : ils travaillent l’été pour payer leurs études ou leur loyer d’étudiant. »'
),
-- Combinaison 10
(
    'Combinaison 10',
    'Vous voulez partir en week-end avec vos amis le mois prochain. Vous leur écrivez un message pour décrire votre projet (lieu, transport, activités, etc.).',
    'COURRIER DES LECTEURS - Tout quitter pour partir en voyage pendant un an: bonne ou mauvaise idée ? Répondez sur notre site Internet : “voyage.internaute.fr”. Vous écrivez un message sur ce site internet, vous répondez à la question posée en prenant des exemples de votre vie personnelle.',
    'Tâche 3 : Le Travail : Favorable ou Défavorable ?\n\nDocument 1 :\nLe travail est au centre de notre vie. Dès l’enfance, on entend souvent la question : «Qu’est-ce que tu veux faire quand tu seras grand ? ». Le travail devrait être synonyme de réussite et de satisfaction, mais il est trop souvent synonyme de fatigue et d’emprisonnement. Aujourd’hui, beaucoup pensent que l’on ne passe pas assez de temps avec sa famille, ses amis. Il est urgent de revoir la place occupée par le travail dans notre société. Certains pensent que travailler moins permettrait d’avoir plus de temps libre pour mieux vivre.\n\nDocument 2 :\nCertaines personnes ont décidé d’arrêter de travailler pour changer de mode de vie. Pourtant, aujourd’hui, travailler, c’est exister La question : « Qu’est-ce que tu fais dans la vie ?» revient souvent lors d’une première rencontre. Elle prouve que l’emploi fait partie de notre identity. D’après le spécialiste Jean-Daniel Remond, la vie en entreprise est très importante. Les contacts quotidiens, les réseaux, les amitiés, l’impression d’être utile, mais aussi les difficultés, tout cela contribue à construire notre personnalité et notre identité.'
),
-- Combinaison 9
(
    'Combinaison 9',
    'Vous répondez à ce message sur le forum. Vous parlez de votre pays et de votre culture. Vous essayez de donner envie aux internautes de découvrir votre pays',
    'Vous avez commencé un nouveau travail. Vous écrivez un courriel à vos amis pour leur raconter comment s’est passée votre première semaine et ce que vous pensez de ce nouveau poste',
    'Tâche 3 : Égalité homme-femme\n\nDocument 1 :\n« Une des valeurs fondamentales du Québec est l’égalité entre les hommes et les femmes. Ils ont les mêmes droits et les mêmes obligations. Les femmes peuvent exercer le métier ou la profession de leur choix. Elles sont présentes aux postes de décision ; elles sont par exemple députées, mairesses, conseillères, administratrices ou dirigeantes de grandes entreprises. Beaucoup d’entre elles ont des métiers et des professions traditionnellement réservées aux hommes. »\n\nDocument 2 :\n« C’est la première journée de cours pour Louis. Ce jeune homme de 27 ans est le seul étudiant masculin de sa classe. Diplômé, il sera aussi le tout premier homme sage-femme au Québec. C’est en travaillant comme masseur auprès de femmes enceintes qu’il a su que le métier de sage-femme était fait pour lui. Aider les femmes à mettre leur bébé au monde est une profession pratiquée depuis toujours par les femmes. L’arrivée d’un homme dans le programme de formation est la bienvenue, mais sa présence peut encore surprendre les patients. »'
),
-- Combinaison 8
(
    'Combinaison 8',
    'Votre ami souhaite commencer à faire du sport. Rédigez un message pour lui recommander une salle de sport située dans votre quartier (localisation, tarifs, types d’activités, etc.).',
    'Vous avez participé à un événement qui vous a marqué (anniversaire, mariage, etc.). Racontez votre souvenir en décrivant ce qui vous a le plus marqué.',
    'Tâche 3 : La Lecture Pour Les Enfants.\n\nDocument 1 :\nAvec l’avancée technologique et les produits high-tech qui envahissent de plus en plus notre quotidien, nos enfants oublient la lecture et s’intéressent davantage aux jeux vidéo, aux sports, à la musique… Contrairement à nous les adultes, dont beaucoup d’entre-nous ont lu des milliers de pages, la génération actuelle est toujours occupée par les réseaux sociaux et le gaming ou prennent du plaisir à pratiquer du sport qui attirent davantage de jeunes grâce aux stars internationales du football, du tennis, de l’athlétisme… alors avec tout ça, pourquoi devons-nous forcer les enfants à lire un bouquin ? Et comme le dit un proverbe, ‘’ le goût de la lecture ne peut pas s’imposer’’… il faut laisser l’enfant choisir ce qu’il veut lire et surtout ne pas l’obliger à lire quand il n’a pas envie.\n\nDocument 2 :\nL’amour de la lecture se transmet de génération en génération bien que, ces dernières années, on ne trouve plus beaucoup de bouquins entre les mains des enfants, laissant la place aux smartphones et aux tablettes. En apprenant à lire régulièrement, l’enfant acquiert le langage plus aisément tout en développant sa capacité d’audition et de concentration. De plus, et pour prendre du plaisir ensemble, les parents peuvent consacrer quotidiennement 10 minutes à leurs enfants pour lire des bouquins ; une activité qui renforcera à coup sûr la complicité parent/enfant'
),
-- Combinaison 7
(
    'Combinaison 7',
    'Écrivez un courriel à vos amis pour les inviter à un anniversaire surprise de votre meilleur(e) ami(e). (Lieu, date, horaire, etc.).',
    'Vous avez participé à une brocante (achat / vente de produits d’occasion) dans votre ville. Sur votre blog personnel, racontez pourquoi vous avez aimé cette activité.',
    'Tâche 3 : Les Vols A Bas Prix\n\nDocument 1 :\nJe fais souvent mes voyages avec des compagnies aériennes à bas prix. Les compagnies Lowcost mettent à disposition des prix inférieurs à ceux proposés par les compagnies aériennes régulières. Cela me coûte des fois moins chère que de voyager en voiture ou en train. Avec ces tarifs-là, vous en doutez qu’il y a un hic, en effet, vous n’aurez le droit à aucun service à bord (ni aliments, ni boissons). Je dirais donc, que le low-cost n’est surtout pas fait pour les vols long courrier.\n\nDocument 2 :\nRécemment, j’ai pris la décision de ne plus voyager avec les compagnies aériennes à bas prix. En effet, j’ai longuement réfléchi afin de prendre ma décision, mais ce choix était évident : des sièges inconfortables, des conditions de travail pénibles et surtout des avions vétustes qui remettent en cause la sécurité ! Dès lors, pour certains voyages, je vais opter pour la voiture ou même le train, ce dernier permet même de découvrir de jolis paysages. Quant aux longs trajets, vaut mieux prendre un vol en compagnie régulière.'
),
-- Combinaison 6
(
    'Combinaison 6',
    'Vous voulez changer la décoration de votre appartement (meubles, peinture, objets,etc.). Vous écrivez un message à un(e) ami(e). Vous lui décrivez votre projet et vous lui demandez de vous aider',
    '« Ecole De Musique ! Cours Gratuits, Concerts, Jeux. Rendez-Vous Vendredi, À partir de 9 Heures » Vous avez participé à cet évènement. Vous écrivez à vos amis pour raconter votre expérience et vous donnez votre opinion sur cette journée.',
    'Tâche 3 : Faut-il faire ses courses dans des petits magasins ou dans des supermarchés ?\n\nDocument 1 :\nLe supermarché est très pratique ; on y trouve une grande variété de produits, tous à portée de main. Vous pouvez garer votre voiture dans le parking et faire le tour des rayons pour acheter tout ce dont vous avez besoin : fruits, légumes, fromages, viandes, boissons… De plus, les supermarchés offrent plusieurs marques pour un même produit, tout en proposant régulièrement des promotions et des remises.\n\nDocument 2 :\nASSOCIATION POUR LA SAUVEGARDE DES PETITS COMMERCES\nLe défi « Février sans supermarché » a été réduit pour limiter la superpuissance des supermarchés et, par conséquent, permettre aux petits commerces de survivre et de réaliser des chiffres d’affaires plus conséquents. Ce défi consiste à boycotter les supermarchés pendant une durée d’un mois, en faisant toutes ses courses dans les épiceries de quartier. Le client aura tout à gagner : il bénéficiera non seulement de produits frais de meilleure qualité, mais aura également l’opportunité de papoter avec les voisins.'
),
-- Combinaison 5
(
    'Combinaison 5',
    '« Je cherche un vélo en bon état et bon marché. Contactezmoi par courriel : mathieu@gmail.com » Vous avez un vélo à vendre. Vous écrivez un courriel pour décrire votre vélo et proposer un prix. Vous lui Donnez un RDV pour essayer le vélo.',
    'Vous avez passé une journée à la campagne avec vos amis. À votre retour, vous écrivez un message sur votre forum pour raconter à vos amis comment cette journée s’est passée. Vous expliquez ce que vous avez aimé (activités, lieu, animaux, etc…)',
    'Tâche 3 : La sévérité des parents envers les enfants\n\nDocument 1 :\nJe vais bientôt avoir 22 ans et j’habite toujours chez mes parents. Mon père et ma mère restent autoritaires avec moi, même si je suis majeure. Quand j’étais mineure, je n’avais pas le droit de dormir dehors, ni même de dépasser 21h lorsque je sortais avec des amies. Maintenant, peu de choses ont changé ; certes, j’ai le droit de veiller plus tard la nuit, mais ma mère ne cesse de m’appeler sur mon téléphone portable jusqu’à ce que je sois de retour.\n\nDocument 2 :\nLes parents ont parfois peur d’être trop sévères avec leurs enfants. Ils craignent, qu’à cause d’un excès d’autorité, leurs enfants ne s’épanouissent pas et manquent plus tard de personnalité. Même si les parents acceptent, par amour, tout ce dont leurs enfants demandent, cela pourrait avoir des effets négatifs lorsqu’ils passent à l’âge adulte. En effet, pour vivre en communauté, il y a certaines règles à respecter.'
),
-- Combinaison 4
(
    'Combinaison 4',
    'Écrivez un message pour inviter vos amis à une fête de fin d’année.',
    'Vous avez passé des vacances au Canada par le biais d’une agence de voyage. Écrivez un commentaire pour raconter votre expérience que vous avez vécue durant ce voyage.',
    'Tâche 3 : Limitation Des Voitures Dans Les Centres-Villes.\n\nDocument 1 :\nAvec des taux de pollution alarmants constatés dans plusieurs endroits dans le monde, plusieurs villes ont réussi leur pari d’interdire la circulation des voitures en zones urbaines. La capitale de Norvège, Oslo, a récemment opté pour cette solution et s’en félicite estimant que c’est une décision bénéfique pour tout le monde. Après un certain temps, les accidents diminueront, la dépendance au pétrole baissera et la qualité d’air sera meilleure !\n\nDocument 2 :\nBeaucoup de villes se lancent dans des projets d’interdiction de voitures en zone urbaine sans mettre en place les outils et les infrastructures nécessaires pour réussir cette transition. Certes, en diminuant les voitures, on aura moins pollué, mais en contrepartie, il faut prévoir entre autres de gigantesques parkings pour garer les voitures, opter davantage pour le transport en commun (métros et Bus) et prévoir des autorisations de circulation pour certains corps de métier (comme la police, les urgentistes, les livreurs, etc.).'
),
-- Combinaison 3
(
    'Combinaison 3',
    'Ecrivez un message à votre ami(e) qui souhaite suivre des cours de langue dans votre école. Donnez les détails spécifiques pour aider votre ami(e) à faire son choix. (lieu, tarifs, types de cours disponible, etc.).',
    'Vous travaillez dans une association qui aident les personnes âgées. Rédigez un un article de blog pour raconter vos expériences et convaincre d’autres personnes de rejoindre l’association.',
    'Tâche 3 : Les animaux de compagnie pour les enfants, pour ou contre ?\n\nDocument 1 :\nOffrir un animal de compagnie à un enfant présente de nombreux avantages, comme le soulignent beaucoup de psychologues. Pour des enfants qui n’ont pas des frères et/ou des sœurs, l’animal est un compagnon qui leur évitera la solitude. Grâce à lui, un enfant prendra confiance en lui et il apprendra vite qu’un animal est un être vivant qui a besoin d’attention et de respect. En sa présence, l’enfant se sentira en sécurité et pourra agir de manière autonome, sans l’aide de ses parents.\n\nDocument 2 :\nBeaucoup d’enfants demandent, un jour ou l’autre, un animal à leurs parents, le plus souvent un chien ou un chat. Mais même si vous avez envie de faire plaisir à votre enfant, il vaut mieux réfléchir sérieusement avant d’acheter un animal domestique. L’animal devient un nouveau membre de la famille et représente un engagement sur de nombreuses années. Or, avoir un animal coûte souvent très cher, et c’est une grande responsabilité. On ne peut pas le traiter comme un jouet que l’on met à la poubelle quand l’enfant s’en désintéresse.'
),
-- Combinaison 2
(
    'Combinaison 2',
    'Un nouveau restaurant vient d’ouvrir près de chez vous. Vous écrivez à un(e) ami(e) pour lui proposer d’y aller avec vous. Vous décrivez le restaurant (cuisine, prix, décoration, etc.).',
    'Vous avez visité une ville que vous ne connaissiez pas. Vous avez envie de partager votre découverte. Vous postez un message sur un site Internet dédié aux voyages. Racontez votre expérience et expliquez ce qui vous a plu et ce qui vous a déplu dans la ville.',
    'Tâche 3 : Vie en colocation entre adultes.\n\nDocument 1 :\nVivre avec d’autres personnes demande d’avoir une bonne entente et de respecter certaines règles. Il n’est pas toujours possible d’écouter sa musique préférée à volume élevé, d’inviter tous ses amis pour faire la fête ou de laisser de la vaisselle sale dans la cuisine. Chaque individu a des habitudes susceptibles d’irriter les autres. C’est pourquoi il est essentiel d’établir des règles de vie en communauté et de les respecter mutuellement. Il est important de communiquer avec ses colocataires chaque fois qu’un problème survient. L’organisation et la discussion sont les clés d’une colocation réussie ou non.\n\nDocument 2 :\nÊtre adulte et vivre en colocation ? C’est un choix qui permet d’accéder facilement à un logement plus spacieux et économique. Il est vrai que vous n’aurez qu’une chambre pour vous et que vous devrez partager la cuisine, le salon et la salle de bain. Toutefois, une colocation peut inclure une maison avec jardin ou un grand appartement en centre-ville ! De plus, en partageant le loyer et les charges avec vos colocataires, vous réduirez considérablement vos dépenses par rapport à un appartement individuel. Alors que vous n’aurez qu’une chambre pour vous et que vous devrez partager les espaces communs, une colocation offre des opportunités de logements bien plus abordables.'
),
-- Combinaison 1
(
    'Combinaison 1',
    'Écrivez un message dans le journal de votre université pour rechercher un partenaire avec qui faire du sport.',
    'Écrivez dans un article de blog pour raconter votre arrivée dans un pays étranger en donnant vos impressions.',
    'Tâche 3 : Rôle De La Télévision Dans L’éducation Des Enfants.\n\nDocument 1 :\nLa télévision est un outil de communication et de divertissement largement répandu dans notre société moderne. Son influence est incontestable, tant sur les individus que sur la culture en général. Elle permet de diffuser des informations, d’offrir des divertissements variés et de favoriser la diffusion de la culture. La télévision est présente dans de nombreux foyers et constitue une source d’information et de divertissement accessibles à tous. Grâce à sa portée et à sa capacité à toucher un large public, la télévision joue un rôle important dans la transmission des connaissances et la sensibilisation aux enjeux sociaux.\n\nDocument 2 :\nLa télévision peut également présenter certains inconvénients. Les émissions télévisées peuvent parfois véhiculer des stéréotypes, des préjugés et des valeurs discutables. De plus, le temps passé devant la télévision peut réduire le temps consacré à d’autres activités plus enrichissantes, telles que la lecture, les interactions sociales ou la pratique d’un sport. Il est important de faire preuve de discernement et de réguler l’exposition à la télévision, en particulier pour les enfants, afin de préserver un équilibre sain entre les différentes formes d’apprentissage et de divertissement.'
);
